version: '3.8'

services:
  flask_ddbms:
    build: .
    container_name: flask_ddbms
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql_master
    networks:
      - banco_net

  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3315:3306"
    volumes:
      - ./docker/mysql_master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_master/my.cnf:/etc/mysql/my.cnf
      - mysql_master_data:/var/lib/mysql
    networks:
      - banco_net

  mysql_sucursal1:
    image: mysql:8.0
    container_name: mysql_sucursal1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql_sucursal1/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_sucursal1/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql_sucursal1/replicacion.sh:/docker-entrypoint-initdb.d/replicacion.sh
      - mysql_sucursal1_data:/var/lib/mysql
    entrypoint: ["bash", "/docker-entrypoint-initdb.d/replicacion.sh"]
    depends_on:
      - mysql_master
    networks:
      - banco_net


  mysql_sucursal2:
    image: mysql:8.0
    container_name: mysql_sucursal2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql_sucursal2/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_sucursal2/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql_sucursal2/replicacion.sh:/docker-entrypoint-initdb.d/replicacion.sh
      - mysql_sucursal2_data:/var/lib/mysql
    entrypoint: ["bash", "/docker-entrypoint-initdb.d/replicacion.sh"]
    depends_on:
      - mysql_master
    networks:
      - banco_net


  mysql_sucursal3:
    image: mysql:8.0
    container_name: mysql_sucursal3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - ./docker/mysql_sucursal3/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_sucursal3/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql_sucursal3/replicacion.sh:/docker-entrypoint-initdb.d/replicacion.sh
      - mysql_sucursal3_data:/var/lib/mysql
    entrypoint: ["bash", "/docker-entrypoint-initdb.d/replicacion.sh"]
    depends_on:
      - mysql_master
    networks:
      - banco_net


  mysql_credit:
    image: mysql:8.0
    container_name: mysql_credit
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - ./docker/mysql_credit/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_credit/my.cnf:/etc/mysql/my.cnf
      - mysql_credit_data:/var/lib/mysql
    depends_on:
      - mysql_master
    networks:
      - banco_net

  mysql_mercadeo:
    image: mysql:8.0
    container_name: mysql_mercadeo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - ./docker/mysql_mercadeo/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_mercadeo/my.cnf:/etc/mysql/my.cnf
      - mysql_mercadeo_data:/var/lib/mysql
    depends_on:
      - mysql_master
    networks:
      - banco_net

  mysql_admin:
    image: mysql:8.0
    container_name: mysql_admin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_admin
    ports:
      - "3312:3306"
    volumes:
      - ./docker/mysql_admin/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_admin_data:/var/lib/mysql
    networks:
      - banco_net

  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    ports:
      - "6032:6032"   # Panel de administración
      - "6033:6033"   # Entrada de tráfico SQL
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql_sucursal1
      - mysql_credit
    networks:
      - banco_net

networks:
  banco_net:
    driver: bridge

volumes:
  mysql_master_data:
  mysql_sucursal1_data:
  mysql_sucursal2_data:
  mysql_sucursal3_data:
  mysql_credit_data:
  mysql_mercadeo_data:
  mysql_admin_data: